name: cdktf diff
run-name: ${{ github.actor }} diff
on: [push]
jobs: 
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls -la
      - uses: actions/checkout@v4
      - name: ls
        run: ls -la
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install && npm i -g cdktf-cli@latest
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
      - name: python print secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
      - name: Test Terraform
        run: |
          terraform --version
          pwd
          ls -la
          terraform init
      - name: Diff
        run: npm exec cdktf diff
        # run: npx cdktf diff
      # - name: Run Terraform CDK
      #   uses: hashicorp/terraform-cdk-action@v4
      #   with:
      #     cdktfVersion: 0.20.7
      #     terraformVersion: 1.7.5
      #     mode: synth-only