name: cdktf diff
run-name: ${{ github.actor }} diff
on: [push]
jobs: 
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Install dependencies
        run: npm install
      - name: Diff
        run: npx cdktf diff
      - name: Run Terraform CDK
          uses: hashicorp/terraform-cdk-action@v4
          with:
            cdktfVersion: 0.20.7
            terraformVersion: 1.7.5
            mode: plan-only